import { Inter } from "next/font/google";
import "@/sass/style.scss";
import SubHeader from "@/components/header/SubHeader";
import SupHeader from "@/components/header/SupHeader";
import SubFooter from "@/components/footer/SubFooter";
import SupFooter from "@/components/footer/SupFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SubHeader />
        <SupHeader />
        {children}
        <SupFooter />
        <SubFooter />
      </body>
    </html>
  );
}
